---
- name: Hello
  hosts: all
  tasks:
      - name: Merhaba Dunya
        debug:
          msg: "Denemee"
      - name: Merhaba Dunya
        debug:
          msg: "Denemee2"
      - name: packages install
        yum:
          - openssh-server
          - unzip
